### ISSUE TITLE
Proof bar out of sync with prover

### ISSUE THREAD

**Issue by PeterReid** [calebegg/proof-pad-classic#8]
If you put two commands on the same line, you can get ACL2 out of sync with the proof bar. For example, submit and then undo:

```
(defun a () 1) (defun b() 2)
```

When it goes undone, :u is only sent once, leaving `a` defined.

**Comment by calebegg** [comment]
Perhaps it would be good to keep track of how many times we see `^Summary$`, because that would also catch macros that reduce to events. Although not all events print that, so we'd have to watch for those as well. It's troublesome.
